AllCops:
  TargetRubyVersion: 2.4
  Exclude:
      - 'bin/**'
      - 'vendor/**/*'
      - 'example/*'
      - 'use_case_flow.gemspec'
Documentation:
   Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 15